#!/bin/sh

set -e

echo ">>> starting freecad-export $@"

FREECAD=freecadcmd
[[ -n "$INTERACTIVE" ]] && FREECAD="env XDG_SESSION_TYPE= freecad"

BINARY_DIR="$(dirname $(realpath "$0"))"

export FREECAD_USER_HOME=$(mktemp -d /tmp/freecad.XXXXXXX)

freecadcmd -c 'import FreeCADGui as Gui; Gui.setupWithoutGUI()'

$FREECAD ${BINARY_DIR}/freecad-export.py "$@"

rm -rf "${FREECAD_USER_HOME}"
