#!/bin/bash

set -e

TOOL_DIR="$(dirname $(realpath "$0"))"

if [[ "$GIT_DIFFTOOL_DIRDIFF" != "true" ]]; then
	echo "difftool must be executed in dirdiff mode (-d)"
	exit 1
fi

PREVIOUS_DIR="$1"
MODIFIED_DIR="$2"

MODIFIED=$(find "$MODIFIED_DIR" -name "*.FCStd")

for MOD in ${MODIFIED[@]}; do
	RELPATH="${MOD##"${MODIFIED_DIR}"}"

	TMP=$(mktemp -d /tmp/meshdiff.XXXXXXXX)

	mkdir -p "${TMP}/previous/"
	rsync -rtv "${PREVIOUS_DIR}/" "${TMP}/previous/"
	mkdir -p "${TMP}/modified/"
	rsync -rt --exclude=.git --exclude-from=.gitignore "${GIT_WORK_TREE}/" "${TMP}/modified/"

	OLD="${TMP}/previous/${RELPATH}"
	NEW="${TMP}/modified/${RELPATH}"
	OLD_MESH="${TMP}/previous.step"
	NEW_MESH="${TMP}/modified.step"
	DIFF_MESH="${TMP}/diff-output.step"

	export FREECAD_USER_HOME=$(mktemp -d /tmp/freecad.XXXXXXX)

	freecadcmd -c 'import FreeCADGui as Gui; Gui.setupWithoutGUI()'

	${TOOL_DIR}/freecad-export.py "${OLD}" "${OLD_MESH}"
	${TOOL_DIR}/freecad-export.py "${NEW}" "${NEW_MESH}"
	${TOOL_DIR}/freecad-diff.py "$NEW_MESH" "$OLD_MESH" "$DIFF_MESH"

	rm -rf "${FREECAD_USER_HOME}"

	if [[ -f "$DIFF_MESH" ]]; then
		XDG_SESSION_TYPE= freecad "$DIFF_MESH" ${TOOL_DIR}/show-diff.FCMacro
	else
		echo "!!! failed to generate diff for $NEW in $TMP"
		read -p 'Press ENTER to continue'
	fi

	rm -rf "$TMP"
done
