#!/bin/bash

set -e

echo ">>> starting freecad-difftool $@"

FREECAD=freecadcmd
[[ -n "$INTERACTIVE" ]] && FREECAD="env XDG_SESSION_TYPE= freecad"

BASEDIR="$(dirname $(realpath "$0"))"

PREVIOUS_DIR="$1"
MODIFIED_DIR="$2"

if ! [[ "$PREVIOUS_DIR" =~ "left/" ]] || ! [[ "$MODIFIED_DIR" =~ "right/" ]]; then
	echo "ERROR: diff FCStd files by running: git difftool --tool=freecad -d"
	exit 1
fi

MODIFIED=$(find "$MODIFIED_DIR" -name "*.FCStd")

for MOD in ${MODIFIED[@]}; do
	RELPATH="${MOD##"${MODIFIED_DIR}"}"

	TMP=$(mktemp -d /tmp/meshdiff.XXXXXXXX)

	mkdir -p "${TMP}/previous/"
	rsync -rt "${PREVIOUS_DIR}/" "${TMP}/previous/"
	mkdir -p "${TMP}/modified/"
	rsync -rt --exclude=.git --exclude-from=.gitignore "${GIT_WORK_TREE}/" "${TMP}/modified/"

	OLD="${TMP}/previous/${RELPATH}"
	NEW="${TMP}/modified/${RELPATH}"
	OLD_MESH="${TMP}/previous.step"
	NEW_MESH="${TMP}/modified.step"
	DIFF_MESH="${TMP}/diff-output.step"

	export FREECAD_USER_HOME=$(mktemp -d /tmp/freecad.XXXXXXX)

	freecadcmd -c 'import FreeCADGui as Gui; Gui.setupWithoutGUI()'

	$FREECAD ${BASEDIR}/freecad-export.py "${OLD}" "${OLD_MESH}"
	$FREECAD ${BASEDIR}/freecad-export.py "${NEW}" "${NEW_MESH}"
	$FREECAD ${BASEDIR}/freecad-diff.py "$NEW_MESH" "$OLD_MESH" "$DIFF_MESH"

	rm -rf "${FREECAD_USER_HOME}"

	if [[ -f "$DIFF_MESH" ]]; then
		XDG_SESSION_TYPE= freecad "$DIFF_MESH" ${BASEDIR}/show-diff.FCMacro
	else
		echo "!!! failed to generate diff for $NEW in $TMP"
		read -p 'Press ENTER to continue'
	fi

	rm -rf "$TMP"
done
